Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: dictate.Handler
      CodeUri: C:\code\dictateFunction
      Runtime: java11